accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    AccountListView,
    ReceiptListView,
    ReceiptCreateView,
    AccountCreateView,
    ExpenseCategoryCreateView,
    ExpenseCategoryListView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path(
        "accounts/create/",
        AccountCreateView.as_view(),
        name="create_receipt_account",
    ),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_expense_category",
    ),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="list_categories",
    ),
    path("accounts/", AccountListView.as_view(), name="account_list"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.name)


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.name)


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateField(blank=True, null=True)
    purchaser = models.ForeignKey(
        USER_MODEL, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account", related_name="receipts", on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return str(self.vendor) + " purchased by " + str(self.purchaser)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from receipts.models import ExpenseCategory, Receipt, Account

# Create your views here.
class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/receipt_create.html"
    fields = [
        "vendor",
        "total",
        "tax",
        "date",
        "category",
        "account",
    ]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "expense_categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "expense_categories/expense_create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/account_create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("account_list")

receipts/templates/accounts/account_create.html
{% extends 'base.html' %}
{% block content %}
    <body>
        <h1>Create Receipt Account</h1>
        <main>
            <form class="narrow-form" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create Account</button>
            </form>
        </main>
    </body>
{% endblock content %}

receipts/templates/accounts/list.html
{% extends 'base.html' %}
{% block content %}
    <table>
        <caption>
            <h3>Accounts List</h3>
        </caption>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Number of receipts</th>
            </tr>
        </thead>
        <tbody>
            {% for account in account_list %}
                <tr>
                    <td>{{ account.name }}</td>
                    <th>{{ account.number }}</th>
                    <td>{{ account.receipts.all|length }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

receipts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
        <title>Receipts</title>
    </head>
    <body>
        <header>
            <h1>Receipts and Expenses</h1>
            <nav>
                <ul class="navigation">
                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'create_expense_category' %}">Create Category</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'list_categories' %}">Expense Categories</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'create_receipt_account' %}">Create Account</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'account_list' %}">Accounts</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'create_receipt' %}">Create Receipt</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'home' %}">Receipts</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a href="{% url 'signup' %}">Sign Up</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>

receipts/templates/expense_categories/expense_create.html
{% extends 'base.html' %}
{% block content %}
    <body>
        <h1>Create Expense Category</h1>
        <main>
            <form class="narrow-form" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create Category</button>
            </form>
        </main>
    </body>
{% endblock content %}

receipts/templates/expense_categories/list.html
{% extends 'base.html' %}
{% block content %}
    <table>
        <caption>
            <h3>Expense Categories List</h3>
        </caption>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number of receipts</th>
            </tr>
        </thead>
        <tbody>
            {% for expense in expensecategory_list %}
                <tr>
                    <td>{{ expense.name }}</td>
                    <td>{{ expense.receipts.all|length }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <table>
        <caption>
            <h3>Receipts List</h3>
        </caption>
        <thead>
            <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
            </tr>
        </thead>
        <tbody>
            {% for receipt in receipt_list %}
                <tr>
                    <td>{{ receipt.vendor }}</td>
                    <td>{{ receipt.total }}</td>
                    <td>{{ receipt.tax }}</td>
                    <th>{{ receipt.date|date:"m-d-Y" }}</th>
                    <td>{{ receipt.category }}</td>
                    <td>{{ receipt.account }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

receipts/templates/receipts/receipt_create.html
{% extends 'base.html' %}
{% block content %}
    <body>
        <h1>Create a Receipt</h1>
        <main>
            <form class="narrow-form" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create Receipt</button>
            </form>
        </main>
    </body>
{% endblock content %}